[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorist==1.8.6",
    "fastapi[standard]>=0.118.0",
    "uvicorn>=0.37.0",
]
