name: Test Backend
on:
  # Run tests on every push to main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'  # Only run tests if files in the backend directory are changed
  
  # Allow manual triggering of this workflow    
  workflow_dispatch:
    
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: uv sync
      working-directory: ./backend/

    - name: Run unit tests
      run: uv run pytest
      working-directory: ./backend/